# Setting the maximum number of retry. Zero to disable retry.
retry_limit = 5 # Retry 5 times. Each time after 5 seconds
address = "failover:(tcp://192.168.72.249:61616)" # Broker address
topic = "XP-S76-Debug" # Name of topic

# Getting a float dataref
[[Data]] # Each dataref is an Data table
name = "airspeed" # User specify name of the dataref, which will be used to access data later
string = "sim/flightmodel/position/indicated_airspeed" # Dataref
type = "float" # Type of the dataref. Can be either "int", "float" or "char"

# Getting a float array dataref
[[Data]]
name = "fuel_flow"
string = "sim/cockpit2/engine/indicators/fuel_flow_kg_sec"
type = "float"
# If "start_index" and "num_value" present in the table, that dataref will be treated as an array of value
start_index = 0 # The start index of the array that Ditto should start reading from
num_value = 2 # Number of value after the start_index Ditto should read.

# Getting a string dataref
[[Data]]
name = "legs_full"
string = "laminar/B738/fms/legs"
type = "char"

# Getting a string dataref with an offset
[[Data]]
name = "legs_offset"
string = "laminar/B738/fms/legs"
type = "char"
start_index = 2

# Getting part of string dataref
[[Data]]
name = "legs_part"
string = "laminar/B738/fms/legs"
type = "char"
start_index = 2
num_value = 10